### ISSUE TITLE
USDZ animation works on MacOS but not on iOS

### ISSUE THREAD

**Issue by enzyme69** [kcoley/gltf2usd#116]
[puppet_share.zip](https://github.com/kcoley/gltf2usd/files/2648788/puppet_share.zip)

It's driving me mad when USDZ works on MacOS, but simply crashes on iOS without any error handling,...

The scene is basically some kind of flat puppets and everything is simple:

<img width="615" alt="screen shot 2018-12-05 at 11 33 15 pm" src="https://user-images.githubusercontent.com/3952687/49513784-37f88300-f8e6-11e8-9d83-ceee56c22edf.png">
[puppet_share.zip](https://github.com/kcoley/gltf2usd/files/2648791/puppet_share.zip)

Not sure why it crashes on iOS...

**Comment by enzyme69** [comment]
Ok I will try doing that. As for iOS 12.1.1, it's still crashing. 

Not sure if this related to previous thread on: not to use multiple color objects or something. Maybe not.

**Comment by enzyme69** [comment]
I tried joining all the meshes into a single mesh, hoping that a single mesh + a single bone chain would do it, but when converting the GLTF, I am getting this error:

```
Traceback (most recent call last):
  File "gltf2usd.py", line 806, in <module>
    convert_to_usd(os.path.expanduser(args.gltf_file), os.path.abspath(os.path.expanduser(args.usd_file)), args.fps, args.scale, args.arkit, args.verbose, args.use_euler_rotation, args.optimize_textures)
  File "gltf2usd.py", line 754, in convert_to_usd
    usd = GLTF2USD(gltf_file=gltf_file, usd_file=usd_file, fps=fps, scale=scale, verbose=verbose, use_euler_rotation=use_euler_rotation, optimize_textures=optimize_textures)
  File "gltf2usd.py", line 55, in __init__
    self.gltf_loader = GLTF2Loader(gltf_file, optimize_textures)
  File "/Users/jimmygunawan/Desktop/puppet_share/_gltf2usd/gltf2loader.py", line 118, in __init__
    self._initialize()
  File "/Users/jimmygunawan/Desktop/puppet_share/_gltf2usd/gltf2loader.py", line 124, in _initialize
    self._initialize_materials()
  File "/Users/jimmygunawan/Desktop/puppet_share/_gltf2usd/gltf2loader.py", line 159, in _initialize_materials
    material = Material(material_entry, i, self)
  File "/Users/jimmygunawan/Desktop/puppet_share/_gltf2usd/gltf2/Material.py", line 115, in __init__
    self._pbr_metallic_roughness = PbrMetallicRoughness(material_entry['pbrMetallicRoughness'], gltf_loader) if ('pbrMetallicRoughness' in material_entry) else None
  File "/Users/jimmygunawan/Desktop/puppet_share/_gltf2usd/gltf2/Material.py", line 67, in __init__
    self._base_color_texture = Texture(pbr_metallic_roughness_entry['baseColorTexture'], gltf_loader) if ('baseColorTexture' in pbr_metallic_roughness_entry) else None
  File "/Users/jimmygunawan/Desktop/puppet_share/_gltf2usd/gltf2/Material.py", line 17, in __init__
    self._image = gltf_loader.get_images()[texture_entry['index']]
IndexError: list index out of range
```

**Comment by enzyme69** [comment]
The issue seems to be resolved after I deleted one of the material that might be overlapping with the mesh. And... the resulting USDZ is now working actually!

I am sending this "bug" to Apple. 

CONCLUSION for now:
Multiple meshes skinned into a single armature is not working on iOS, can still work on MacOS.
