### ISSUE TITLE
Index out of range errors

### ISSUE THREAD

**Issue by wave-electron** [kcoley/gltf2usd#12]
I've notice a number of times I've got index out of range errors. 

in the most recent case it occurred inside of   **def _store_joint_animations**

I add the following exception handling. I think it was happening because the models had several bone branches (rather complex bone animation). 

Anyway I modified the following code which at least enabled the usda file to build. The usda animation still won't run!  But the usda file itself at least builds with the correct mesh & materials.

 ```
 try:
        scale[0] = skeleton_joint.GetRestTransformsAttr().Get()[joint_index].GetRow3(0).GetLength()
        scale[1] = skeleton_joint.GetRestTransformsAttr().Get()[joint_index].GetRow3(1).GetLength()
        scale[2] = skeleton_joint.GetRestTransformsAttr().Get()[joint_index].GetRow3(2).GetLength()
                
except IndexError:
                    return
```

I'm guessing the command tool will need a bit more error handling for it to function more smoothly with the large variations or cases it would encounter.

**Comment by kcoley** [comment]
@wave-electron thanks for your investigation.  I agree that there should be more exception handling with the various files being imported from various DCC tools.  I plan on making some significant updates to the skeleton logic to handle some edge cases that like attached nodes and joints mapping to USD from glTF.

**Comment by kcoley** [comment]
@wave-electron do you have a model handy that can repro this issue?

**Comment by wave-electron** [comment]
@kcoley 

```
iMac:COLLADA2GLTF ashleyjoyce$ python gltf2usd.py -g Start_Walking.gltf -o Start_Walking.usda -v
Traceback (most recent call last):
  File "gltf2usd.py", line 1124, in <module>
    convert_to_usd(args.gltf_file, args.usd_file, args.fps, args.verbose)
  File "gltf2usd.py", line 1113, in convert_to_usd
    GLTF2USD(gltf_file=gltf_file, usd_file=usd_file, fps=fps, verbose=verbose)
  File "gltf2usd.py", line 64, in __init__
    self.convert()
  File "gltf2usd.py", line 1099, in convert
    self.convert_nodes_to_xform()
  File "gltf2usd.py", line 100, in convert_nodes_to_xform
    self._convert_animations_to_usd()
  File "gltf2usd.py", line 510, in _convert_animations_to_usd
    self._convert_skin_animations_to_usd()
  File "gltf2usd.py", line 634, in _convert_skin_animations_to_usd
    self._store_joint_animations(usd_animation, joint_values, joint_map)
  File "gltf2usd.py", line 666, in _store_joint_animations
    scale[0] = skeleton_joint.GetRestTransformsAttr().Get()[joint_index].GetRow3(0).GetLength()
IndexError: Index out of range.
```
Here is the glTF files. It was built with the fbx2glFT command tool
[Start_Walking.zip](https://github.com/kcoley/gltf2usd/files/2331062/Start_Walking.zip)

glTF Animation works as expected in the sandbox.babylon.com. 

BTW, great progress today!

**Comment by wave-electron** [comment]
@kcoley 

After I add my error handling of the indexError above on your latest commit today . The usda file builds. If you open in Xcode Beta 6, the animation plays, but its all distorted (see screen shot below)

<img width="350" alt="example" src="https://user-images.githubusercontent.com/16273780/44771184-a1614b00-abad-11e8-9404-641dfd524053.png">

If you now open the same usda file in Xcode beta 5 you get the correct rest pose, but no animation will play. 

<img width="350" alt="example2" src="https://user-images.githubusercontent.com/16273780/44771242-d40b4380-abad-11e8-8d4e-c6aabc2c5ba2.png">

**Comment by kcoley** [comment]
@wave-electron I implemented and merged your exception handler to master.  I am not sure about the animation in XCode, but I might try to see if I can get it to work with the Maya USD importer to see how it behaves there.
