### ISSUE TITLE
Warning: in _CreateNewUsdzPackage

### ISSUE THREAD

**Issue by sayduck-daniel** [kcoley/gltf2usd#179]
We are getting this error more and more often on our implementation.

Is this a known issue?

```
Conversion complete!
created /tmp/tmpcpipak/dist.usdc
created /tmp/tmpcpipak/dist.usdc
Warning: in _CreateNewUsdzPackage at line 1130 of /tmp/USD-19.07/pxr/usd/lib/usdUtils/dependencies.cpp -- Failed to add temporary layer at '/var/tmp/dist.usdc' to the package at path 'dist.usdz'.
Traceback (most recent call last):
  File "/usr/local/gltf2usd/Source/gltf2usd.py", line 923, in <module>
    convert_to_usd(os.path.expanduser(args.gltf_file), os.path.abspath(os.path.expanduser(args.usd_file)), args.fps, args.scale, args.arkit, args.verbose, args.use_euler_rotation, args.optimize_textures, args.generate_texture_transform_texture, args.scale_texture)
  File "/usr/local/gltf2usd/Source/gltf2usd.py", line 878, in convert_to_usd
    success = UsdUtils.CreateNewUsdzPackage(resolved_asset, temp_usd_file) and success
pxr.Tf.ErrorException: 
    Error in 'pxrInternal_v0_19__pxrReserved__::UsdZipFileWriter::AddFile' at line 814 in file /tmp/USD-19.07/pxr/usd/lib/usd/zipFile.cpp : 'Failed to map '/var/tmp/dist.usdc': No such file or directory'```

**Comment by ephb** [comment]
The warning about the temporary files is a known issue.
