### ISSUE TITLE
Unicode Encode Error and another Syntax error

### ISSUE THREAD

**Issue by enzyme69** [kcoley/gltf2usd#25]
This Sketchfab model is also problematic:
https://sketchfab.com/models/60a1ff80a22a48c09833a403b5f48b73

```bash
Warning: in _InitWithString at line 106 of /Users/jimmygunawan/Projects/Pixar/USD/pxr/usd/lib/sdf/path.cpp -- Ill-formed SdfPath <RootNode (gltf_orientation_matrix)/RootNode (model_correction_matrix)/Marie_rose_motion_INTRO_pose_fbx//RootNode/_arm//_rootJoint>: syntax error
Traceback (most recent call last):
  File "gltf2usd.py", line 1126, in <module>
    convert_to_usd(args.gltf_file, args.usd_file, args.fps, args.scale, args.verbose)
  File "gltf2usd.py", line 1114, in convert_to_usd
    GLTF2USD(gltf_file=gltf_file, usd_file=usd_file, fps=fps, scale=scale, verbose=verbose)
  File "gltf2usd.py", line 70, in __init__
    self.convert()
  File "gltf2usd.py", line 1100, in convert
    self.convert_nodes_to_xform()
  File "gltf2usd.py", line 104, in convert_nodes_to_xform
    self._convert_node_to_xform(node, node_index, xform_name)
  File "gltf2usd.py", line 157, in _convert_node_to_xform
    self._convert_node_to_xform(self.gltf_loader.json_data['nodes'][child_index], child_index, xform_path + '/node{}'.format(child_index))
  File "gltf2usd.py", line 157, in _convert_node_to_xform
    self._convert_node_to_xform(self.gltf_loader.json_data['nodes'][child_index], child_index, xform_path + '/node{}'.format(child_index))
  File "gltf2usd.py", line 157, in _convert_node_to_xform
    self._convert_node_to_xform(self.gltf_loader.json_data['nodes'][child_index], child_index, xform_path + '/node{}'.format(child_index))
  File "gltf2usd.py", line 157, in _convert_node_to_xform
    self._convert_node_to_xform(self.gltf_loader.json_data['nodes'][child_index], child_index, xform_path + '/node{}'.format(child_index))
  File "gltf2usd.py", line 157, in _convert_node_to_xform
    self._convert_node_to_xform(self.gltf_loader.json_data['nodes'][child_index], child_index, xform_path + '/node{}'.format(child_index))
  File "gltf2usd.py", line 157, in _convert_node_to_xform
    self._convert_node_to_xform(self.gltf_loader.json_data['nodes'][child_index], child_index, xform_path + '/node{}'.format(child_index))
  File "gltf2usd.py", line 157, in _convert_node_to_xform
    self._convert_node_to_xform(self.gltf_loader.json_data['nodes'][child_index], child_index, xform_path + '/node{}'.format(child_index))
  File "gltf2usd.py", line 153, in _convert_node_to_xform
    self._convert_mesh_to_xform(self.gltf_loader.json_data['meshes'][node['mesh']], usd_parent_node, node_index, skin_index )
  File "gltf2usd.py", line 177, in _convert_mesh_to_xform
    self._convert_primitive_to_mesh(name=mesh_primitive_name, primitive=mesh_primitive, usd_parent_node=usd_parent_node, node_index=node_index, double_sided = double_sided, skin_index=skin_index)
  File "gltf2usd.py", line 238, in _convert_primitive_to_mesh
    self._convert_skin_to_usd(gltf_node, node_index, usd_parent_node, mesh)
  File "gltf2usd.py", line 741, in _convert_skin_to_usd
    name = self._convert_to_usd_friendly_node_name(self._get_joint_name(node))
  File "gltf2usd.py", line 549, in _get_joint_name
    name = '{0}/{1}'.format(n.name, name)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-11: ordinal not in range(128)
```

**Comment by kcoley** [comment]
@enzyme69 looks like this file has some strings with some weird encodings.  I can add a fallback in case the strings cannot be encoded

**Comment by wave-electron** [comment]
Anime character... most likely Japanese character set on the bone names!

**Comment by ox** [comment]
What would be the fix here? Does USD support Unicode names or would this have to be converted/hashed?

**Comment by kcoley** [comment]
@ox I think the fix would be to either create a name with the node and node index(i.e. 'node_{}'.format(node_index), or load and write out the unicode.  Based on some USD unit tests it seems that unicode strings should be supported in USD, though I am not sure how that will play with usdz on iOS

**Comment by kcoley** [comment]
@enzyme69 @ox I merged a fix for unicode characters a few days ago.  Unicode characters now get converted to ascii.  Though this particular model takes a long time to convert.
